# To obtain a app password:
# https://myaccount.google.com/apppasswords

gmail_app_username: bsutton@onepub.dev
gmail_app_password: vbbf hrcw aucv qblf
path_to_static_content: /home/bsutton/git/handyman/ihserver/www_root
lets_encrypt_live: /home/bsutton/git/handyman/ihserver/test/letsencrypt/live
fqdn: squarephone.biz
domain_email: bsutton@onepub.dev
https_port: 10443
http_port: 1080
production: false
binding_address: 0.0.0.0
logger_path: console
use_https: false
debug: true
hmb_api_token: "abc 1234"
booking_requests_path: /home/bsutton/git/handyman/ihserver/config/booking_requests.json
