name: booking_request
version: 0.1.0
publish_to: https://onepub.dev/api/jbbxpsdavu/
description: Shared booking request model for handyman apps.

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:

dev_dependencies:
  lint_hard: ^6.0.0
  test: ^1.25.0
